<?xml version="1.0" encoding="utf-8"?><Database Name="vfms_db" Class="vfmsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local)\MSSQLSERVER_R2;Initial Catalog=vfms_db;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="vfms_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.member" Member="members">
    <Type Name="member">
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="mem_address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="mem_id_card" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mem_reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mem_runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_group_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_user" Member="usergroup" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.usergroup" Member="usergroups">
    <Type Name="usergroup">
      <Column Name="user_group_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_group_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="display_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_user" Member="users" ThisKey="user_group_id" OtherKey="user_group_id" Type="user" />
      <Association Name="usergroup_usergroup_role" Member="usergroup_role" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup_role" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.usergroup_role" Member="usergroup_roles">
    <Type Name="usergroup_role">
      <Column Name="user_group_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_usergroup_role" Member="usergroup" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup" IsForeignKey="true" />
    </Type>
  </Table>
</Database>