<?xml version="1.0" encoding="utf-8"?><Database Name="vfms_db" Class="vfmsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local)\MSSQLSERVER_R2;Initial Catalog=vfms_db;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="vfms_dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.contract_acc1" Member="contract_acc1s">
    <Type Name="contract_acc1">
      <Column Name="contract1_no" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="la1_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cacc1_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cacc1_period" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc1_int_rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc1_person1" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cacc1_person2" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.contract_acc2" Member="contract_acc2s">
    <Type Name="contract_acc2">
      <Column Name="contract2_no" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="la2_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cacc2_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cacc2_period" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc2_int_rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc2_person1" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="cacc2_person2" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.depo_interest" Member="depo_interests">
    <Type Name="depo_interest">
      <Column Name="dint_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dint_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="member_depo_interest" Member="member" ThisKey="mem_id" OtherKey="mem_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.deposit_account" Member="deposit_accounts">
    <Type Name="deposit_account">
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="depo_total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="deposit_account_depo_transaction" Member="depo_transactions" ThisKey="mem_id" OtherKey="mem_id" Type="depo_transaction" />
      <Association Name="member_deposit_account" Member="member" ThisKey="mem_id" OtherKey="mem_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.dividend" Member="dividends">
    <Type Name="dividend">
      <Column Name="div_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lmem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="div_ratio" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="div_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="loan_member_dividend" Member="loan_member" ThisKey="lmem_id" OtherKey="lmem_id" Type="loan_member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loan_member" Member="loan_members">
    <Type Name="loan_member">
      <Column Name="lmem_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lmem_reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="lmem_runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="loan_member_dividend" Member="dividends" ThisKey="lmem_id" OtherKey="lmem_id" Type="dividend" />
      <Association Name="member_loan_member" Member="member" ThisKey="mem_id" OtherKey="mem_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.member" Member="members">
    <Type Name="member">
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="mem_address" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="mem_id_card" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="mem_reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mem_runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="member_depo_interest" Member="depo_interests" ThisKey="mem_id" OtherKey="mem_id" Type="depo_interest" />
      <Association Name="member_deposit_account" Member="deposit_account" ThisKey="mem_id" OtherKey="mem_id" Type="deposit_account" Cardinality="One" />
      <Association Name="member_loan_member" Member="loan_members" ThisKey="mem_id" OtherKey="mem_id" Type="loan_member" />
      <Association Name="member_loan_member_acc1" Member="loan_member_acc1s" ThisKey="mem_id" OtherKey="mem_id" Type="loan_member_acc1" />
      <Association Name="member_loan_member_acc2" Member="loan_member_acc2s" ThisKey="mem_id" OtherKey="mem_id" Type="loan_member_acc2" />
    </Type>
  </Table>
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_group_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="full_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_user" Member="usergroup" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.usergroup" Member="usergroups">
    <Type Name="usergroup">
      <Column Name="user_group_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="user_group_name" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="display_order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_user" Member="users" ThisKey="user_group_id" OtherKey="user_group_id" Type="user" />
      <Association Name="usergroup_usergroup_role" Member="usergroup_role" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup_role" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.usergroup_role" Member="usergroup_roles">
    <Type Name="usergroup_role">
      <Column Name="user_group_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="role_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="usergroup_usergroup_role" Member="usergroup" ThisKey="user_group_id" OtherKey="user_group_id" Type="usergroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loan_account1" Member="loan_account1s">
    <Type Name="loan_account1">
      <Column Name="lmem1_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="la1_balance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="loan_account1_loan_member_acc1" Member="loan_member_acc1" ThisKey="lmem1_id" OtherKey="lmem1_id" Type="loan_member_acc1" Cardinality="One" />
      <Association Name="loan_account1_loan_acc1_transaction" Member="loan_acc1_transactions" ThisKey="lmem1_id" OtherKey="lmem1_id" Type="loan_acc1_transaction" />
    </Type>
  </Table>
  <Table Name="dbo.loan_member_acc1" Member="loan_member_acc1s">
    <Type Name="loan_member_acc1">
      <Column Name="lmem1_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lmem1_reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cacc1_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cacc1_period" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc1_int_rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc1_person1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc1_person2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="booking_by" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="loan_account1_loan_member_acc1" Member="loan_account1" ThisKey="lmem1_id" OtherKey="lmem1_id" Type="loan_account1" IsForeignKey="true" />
      <Association Name="member_loan_member_acc1" Member="member" ThisKey="mem_id" OtherKey="mem_id" Type="member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loan_acc1_transaction" Member="loan_acc1_transactions">
    <Type Name="loan_acc1_transaction">
      <Column Name="la1_trans_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lmem1_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="la1_trans_timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="la1_trans_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="la1_trans_rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="booking_by" Type="System.Data.Linq.Binary" DbType="VarBinary(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="loan_account1_loan_acc1_transaction" Member="loan_account1" ThisKey="lmem1_id" OtherKey="lmem1_id" Type="loan_account1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loan_member_acc2" Member="loan_member_acc2s">
    <Type Name="loan_member_acc2">
      <Column Name="lmem2_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="lmem2_reg_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="cacc2_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="cacc2_period" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc2_int_rate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc2_person1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cacc2_person2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="booking_by" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="member_loan_member_acc2" Member="member" ThisKey="mem_id" OtherKey="mem_id" Type="member" IsForeignKey="true" />
      <Association Name="loan_account2_loan_member_acc2" Member="loan_account2" ThisKey="lmem2_id" OtherKey="lmem2_id" Type="loan_account2" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.loan_account2" Member="loan_account2s">
    <Type Name="loan_account2">
      <Column Name="lmem2_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="la2_balance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="loan_account2_loan_member_acc2" Member="loan_member_acc2" ThisKey="lmem2_id" OtherKey="lmem2_id" Type="loan_member_acc2" Cardinality="One" />
      <Association Name="loan_account2_loan_acc2_transaction" Member="loan_acc2_transactions" ThisKey="lmem2_id" OtherKey="lmem2_id" Type="loan_acc2_transaction" />
    </Type>
  </Table>
  <Table Name="dbo.loan_acc2_transaction" Member="loan_acc2_transactions">
    <Type Name="loan_acc2_transaction">
      <Column Name="la2_trans_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="lmem2_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="la2_trans_timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="la2_trans_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="la1_trans_rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="booking_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="loan_account2_loan_acc2_transaction" Member="loan_account2" ThisKey="lmem2_id" OtherKey="lmem2_id" Type="loan_account2" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.depo_transaction" Member="depo_transactions">
    <Type Name="depo_transaction">
      <Column Name="dtrans_id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="dtrans_timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="dtrans_amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="dtrans_total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="mem_id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="booking_by" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="runningNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="deposit_account_depo_transaction" Member="deposit_account" ThisKey="mem_id" OtherKey="mem_id" Type="deposit_account" IsForeignKey="true" />
    </Type>
  </Table>
</Database>