'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dividend2

    '''<summary>
    '''lbl_MoneyLoan1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MoneyLoan1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_dividend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dividend1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_dividend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dividend1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_return1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_return1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_return1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_return1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_board1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_board1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_board1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_board1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_public1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_public1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_public1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_public1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_other1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_other1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_other1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_other1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_risk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_risk1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_risk1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_risk1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_join1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_join1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_join1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_join1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_welfare1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_welfare1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_welfare1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_welfare1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_Dividend1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Dividend1 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_Save1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save1 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''lbl_MoneyLoan2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_MoneyLoan2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_dividend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dividend2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_dividend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_dividend2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_return2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_return2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_return2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_return2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_board2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_board2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_board2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_board2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_public2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_public2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_public2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_public2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_other2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_other2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_other2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_other2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_risk2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_risk2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_risk2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_risk2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_join2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_join2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_join2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_join2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_welfare2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_welfare2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_welfare2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_welfare2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_Dividend2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Dividend2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_Save2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save2 As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''txt_total control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_total As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_rum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_rum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ban control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ban As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_cal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cal As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_save3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save3 As Global.System.Web.UI.HtmlControls.HtmlButton
End Class
