'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManageUser

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lbl_UserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UserGroup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddl_UserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_UserGroup As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lv_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lv_User As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''sds_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_User As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''Pnl_TopUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_TopUser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''chk_Active control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_Active As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbl_UserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_UserName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_FullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_FullName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div_ChooseUserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_ChooseUserGroup As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_ChooseUserGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ChooseUserGroup As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_UserName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_UserName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_FullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_FullName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''div_DdlGroupUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_DdlGroupUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddl_GroupUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_GroupUser As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dv_BTNUpdateAndInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dv_BTNUpdateAndInsert As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''btn_Update control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Update As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_Insert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Insert As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Pnl_MiddleUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_MiddleUser As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''lbl_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Password As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ConfirmPassword As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Password control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Password As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ConfirmPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ConfirmPassword As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_ChangePassWord control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ChangePassWord As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Pnl_CreateAndDeleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Pnl_CreateAndDeleted As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CreateMemberButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateMemberButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DeleteMemberButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteMemberButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lds_ser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_ser As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.System.Web.UI.WebControls.Label
End Class
