'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PaymentLoan2

    '''<summary>
    '''lbl_Numberloan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Numberloan As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''cmb_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_Number As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''lds_Member control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lds_Member As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''btnName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnName As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cmb_Loan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmb_Loan As Global.DevExpress.Web.ASPxEditors.ASPxComboBox

    '''<summary>
    '''ldr_Loan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldr_Loan As Global.System.Web.UI.WebControls.LinqDataSource

    '''<summary>
    '''btnCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCheck As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_Name1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Name1 As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''lbl_Number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Number As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_Money1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Money1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Money2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Money2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Interest1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Interest1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Interest2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Interest2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lbl_Error control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Error As Global.DevExpress.Web.ASPxEditors.ASPxLabel

    '''<summary>
    '''btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_Uploan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Uploan As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.HtmlControls.HtmlButton

    '''<summary>
    '''ASPxGridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxGridView1 As Global.DevExpress.Web.ASPxGridView.ASPxGridView

    '''<summary>
    '''sds_loan_acc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sds_loan_acc2 As Global.System.Web.UI.WebControls.SqlDataSource
End Class
